#pragma warning disable SA1601
#pragma warning disable S3903
#nullable enable

// Supplements the IToken class generated by CppSharp with properties that we depend on from the C# side
public partial class IToken
{
    public abstract Perlang.TokenType Type { get; }
    public abstract string Lexeme { get; }
    public abstract object? Literal { get; }
    public abstract string FileName { get; }
    public abstract int Line { get; }
}
