#!/usr/bin/env python3
"""
Walks the full commit history of the Perlang repo and counts source lines per
language and category (own / auto-generated / vendored) at one point per
calendar day, using a separate git worktree to check out each commit.

Output is a CSV (or JSON) suitable for plotting "lines of code over time".
"""

import argparse
import csv
import json
import re
import subprocess
import sys
import time
from collections import defaultdict
from pathlib import Path

EXTENSION_LANGUAGE = {
    "per": "perlang",
    "cs": "csharp",
    "cc": "cpp",
    "h": "cpp",
    "c": "c",
}

# Path prefixes (relative to repo root, POSIX separators) that are vendored
# third-party code. The language here is explicit rather than derived from
# the extension, since e.g. libtommath's headers would otherwise be
# misclassified as C++ by the blanket ".h" -> cpp mapping.
VENDOR_PATH_PREFIXES = [
    ("src/stdlib/src/fmt/", "cpp"),
    ("src/stdlib/src/tsl/", "cpp"),
    ("src/stdlib/src/libtommath/", "c"),
]

AUTOGEN_PATTERNS = [
    re.compile(r"Automatically generated code by Perlang"),
    re.compile(r"autogenerated code by CppSharp", re.IGNORECASE),
]

# Auto-generated files that are excluded from the stats entirely (not even
# counted as "auto-generated"), because they add no information beyond what
# is already counted elsewhere. The Perlang-generated C++ bootstrap files
# (perlang_cli.cc/.h) are a 1:1 rendering of the .per stdlib source that's
# already counted as "own" Perlang code -- they're only checked in so that
# building Perlang doesn't require an existing Perlang compiler.
EXCLUDED_CATEGORIES = {
    ("cpp", "auto-generated"),
}

AUTOGEN_SNIFF_BYTES = 500


def run_git(args, cwd, check=True):
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if check and result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def repo_root(path):
    return Path(run_git(["rev-parse", "--show-toplevel"], cwd=path).strip())


def list_commits_by_day(repo, branch):
    """Return [(date, sha), ...] in chronological order, one commit per day
    (the last commit made that day)."""
    out = run_git(
        ["log", "--format=%cd|%H", "--date=format:%Y-%m-%d", branch],
        cwd=repo,
    )
    latest_for_date = {}
    for line in out.splitlines():
        date, sha = line.split("|", 1)
        # Newest-first traversal: first sha seen for a date is that day's
        # latest commit.
        if date not in latest_for_date:
            latest_for_date[date] = sha
    return sorted(latest_for_date.items())


def ensure_worktree(repo, worktree_path, branch):
    if worktree_path.exists():
        return
    worktree_path.parent.mkdir(parents=True, exist_ok=True)
    run_git(["worktree", "add", "--detach", str(worktree_path), branch], cwd=repo)


def classify(rel_path):
    ext = rel_path.rsplit(".", 1)[-1] if "." in rel_path else ""
    for prefix, language in VENDOR_PATH_PREFIXES:
        if rel_path.startswith(prefix):
            return language, "vendored"
    if ext not in EXTENSION_LANGUAGE:
        return None, None
    return EXTENSION_LANGUAGE[ext], None  # category decided by caller (needs file content)


def count_commit(worktree_path):
    """Checkout is assumed to already be done. Returns
    {(language, category): [lines, files]}."""
    files = run_git(["ls-files"], cwd=worktree_path).splitlines()
    stats = defaultdict(lambda: [0, 0])

    for rel_path in files:
        language, category = classify(rel_path)
        if language is None:
            continue

        full_path = worktree_path / rel_path
        try:
            data = full_path.read_bytes()
        except OSError:
            continue

        if category is None:
            sniff = data[:AUTOGEN_SNIFF_BYTES].decode("utf-8", errors="ignore")
            category = "auto-generated" if any(p.search(sniff) for p in AUTOGEN_PATTERNS) else "own"

        if (language, category) in EXCLUDED_CATEGORIES:
            continue

        lines = data.count(b"\n")
        entry = stats[(language, category)]
        entry[0] += lines
        entry[1] += 1

    return stats


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="Path inside the Perlang git repo (default: .)")
    parser.add_argument("--branch", default="master", help="Branch to walk (default: master)")
    parser.add_argument("--worktree", default=None, help="Worktree path (default: sibling dir next to the repo)")
    parser.add_argument("--output", default="langstats.csv", help="Output file (default: langstats.csv)")
    parser.add_argument("--format", choices=["csv", "json"], default="csv")
    parser.add_argument("--limit", type=int, default=None, help="Only process the first N days (for benchmarking)")
    parser.add_argument("--progress-every", type=int, default=25)
    args = parser.parse_args()

    repo = repo_root(Path(args.repo))
    worktree_path = Path(args.worktree) if args.worktree else repo.parent / f"{repo.name}-langstats-worktree"

    print(f"Repo: {repo}")
    print(f"Worktree: {worktree_path}")

    ensure_worktree(repo, worktree_path, args.branch)

    days = list_commits_by_day(repo, args.branch)
    if args.limit:
        days = days[: args.limit]
    print(f"{len(days)} day(s) to process")

    rows = []
    start = time.monotonic()

    for i, (date, sha) in enumerate(days, 1):
        run_git(["checkout", "--quiet", "--force", "--detach", sha], cwd=worktree_path)
        stats = count_commit(worktree_path)
        for (language, category), (lines, files) in stats.items():
            rows.append({"date": date, "language": language, "category": category, "lines": lines, "files": files})

        if i % args.progress_every == 0 or i == len(days):
            elapsed = time.monotonic() - start
            rate = i / elapsed if elapsed > 0 else 0
            eta = (len(days) - i) / rate if rate > 0 else 0
            print(f"  [{i}/{len(days)}] {date} {sha[:8]}  {elapsed:.1f}s elapsed, {rate:.2f} days/s, ETA {eta:.0f}s")

    elapsed = time.monotonic() - start
    print(f"Done in {elapsed:.1f}s ({elapsed / len(days):.3f}s/day)" if days else "Done (no days)")

    rows.sort(key=lambda r: (r["date"], r["language"], r["category"]))

    output_path = Path(args.output)
    if args.format == "csv":
        with output_path.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=["date", "language", "category", "lines", "files"])
            writer.writeheader()
            writer.writerows(rows)
    else:
        output_path.write_text(json.dumps(rows, indent=2))

    print(f"Wrote {len(rows)} rows to {output_path}")


if __name__ == "__main__":
    main()
