name: perlang-install

on: [push]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

          # Disabled since macOS builds are broken since https://gitlab.perlang.org/perlang/perlang/-/merge_requests/506
          #- macos-13

    steps:
      - uses: actions/checkout@v1
      - name: Run perlang-install script
        run: ./scripts/perlang-install
      - name: Output perlang version
        run: $HOME/.perlang/nightly/bin/perlang --version

  # Windows need special treatment, since the default shell for Windows with
  # GitHub actions is Powershell. We do not want to change to 'bash' for the
  # other platforms though, since we want to ensure that the installer works on
  # any POSIX compliant shell.

# Temporary disabled because Windows builds are currently broken:
# https://gitlab.perlang.org/perlang/perlang/-/issues/398
#  install_windows:
#    runs-on: windows-2019
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Run perlang-install script
#        run: ./scripts/perlang-install
#        shell: bash
#      - name: Output perlang version
#        run: $HOME/.perlang/nightly/bin/perlang --version
#        shell: bash
