name: Publish website

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/publish-website.yml
      - docs/**
      - src/**

jobs:
  publish-website:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1

      - name: Install SASS
        run: sudo npm install -g sass

      - name: Rebuild website
        run: make -j docs

      - name: Ensure API docs have expected content
        run: make docs-validate-api-docs

      - name: Deploy to perlang.org repo
        uses: jamesives/github-pages-deploy-action@4.1.0
        with:
          repository-name: perlang-org/perlang.org
          branch: master
          folder: _site
          target-folder: public
          ssh-key: ${{ secrets.WEBSITE_DEPLOY_KEY }}
          git-config-name: perlang.org-ci-uploader
          git-config-email: perlang-ci-uploader@noreply.github.com
