name: Website

# No need to run this on master pushes since publish-website takes care of it
# for that branch.
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Rebuild website
      run: make docs
