name: Website

# No need to run this on master pushes since publish-website takes care of it
# for that branch.
on:
  push:
    branches-ignore:
      - master

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build Perlang & rebuild website
        run: make -j all docs
        env:
          DOCFX_SOURCE_BRANCH_NAME: ${{ env.GIT_BRANCH }}

      - name: Ensure examples execute without errors
        run: make docs-test-examples SHELL="sh -x -e"
