name: Website

# No need to run this on master pushes since publish-website takes care of it
# for that branch.
on:
  push:
    branches-ignore:
      - master

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      #
      # Build web site
      #
      - name: Install SASS
        run: sudo npm install -g sass

      - name: Rebuild website
        run: make -j docs

      - name: Ensure API docs have expected content
        run: make docs-validate-api-docs
